# Generated by Django 3.0 on 2019-12-05 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSMRouterModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address_from', models.CharField(max_length=300, verbose_name='Address From to Start')),
                ('address_to', models.CharField(max_length=300)),
                ('route_opt', models.CharField(max_length=120)),
                ('date_searched', models.DateField(default=datetime.datetime(2019, 12, 5, 22, 40, 44, 939333, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
    ]
