# Generated by Django 3.0 on 2019-12-05 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('osmrouter', '0002_auto_20191205_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmroutermodel',
            name='date_searched',
            field=models.DateField(default=datetime.datetime(2019, 12, 5, 22, 56, 30, 561710, tzinfo=utc)),
        ),
    ]
