# Generated by Django 3.0 on 2019-12-05 23:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('osmrouter', '0005_auto_20191205_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmroutermodel',
            name='date_searched',
            field=models.DateField(default=datetime.datetime(2019, 12, 5, 23, 55, 36, 565807, tzinfo=utc)),
        ),
    ]
